[package]
name = "fusebox"
version = "0.1.0"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]
edition = "2024"

[dependencies]
box-format.workspace = true
fuser.workspace = true
tokio = { workspace = true, features = ["rt"] }
structopt.workspace = true
env_logger.workspace = true
libc.workspace = true
log.workspace = true
